apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-spring-boot-app
  title: sample-spring-boot-app
  annotations:
    github.com/project-slug: 'piomin/sample-spring-boot-app'
    github.com/project-slug: piomin/sample-spring-boot-app
    sonarqube.org/project-key: piomin_sample-spring-boot-app
  tags:
    - spring-boot
    - java
    - maven
    - circleci
    - renovate
    - sonarqube
spec:
  type: service
  owner: piotr.minkowski@gmail.com
  lifecycle: experimental